### PR TITLE
update to extract table title and caption for preprints

### PR DESCRIPTION
**Pull request by KC37**
Without changing the functionality for extracting data from tables in PMCs, I added code to also allow extraction of the title and caption from tables in preprints. Since tables in preprints contain the title and caption as text, whereas the rest of the table is an image, they were identified without rows, so the program did not proceed initially.

### CODE REVIEW

**Comment by Tom-Shorter** [comment]
Thanks for this update, any chance you could make a pull request to a new branch in this repo? Once I've been able to test it myself I'll then merge it into master.

**Comment by KC37** [comment]
> 
> 
> Thanks for this update, any chance you could make a pull request to a new branch in this repo? Once I've been able to test it myself I'll then merge it into master.

I tried, but I couldn't. I think I have to be a collaborator for that.

**Comment by Tom-Shorter** [comment]
I've invited you as a collaborator, hopefully you can make a new branch now.

**Comment by KC37** [comment]
> 
> 
> I've invited you as a collaborator, hopefully you can make a new branch now.

I managed to do what you suggested. Is it okay? I will have to rest a bit as I have my graduation ceremony today.

**Comment by Tom-Shorter** [comment]
I'll have to test it a bit when I have a chance but if there are any changes that need to be made then don't worry about it, I'll handle them. You should focus on enjoying your graduation, and congratulations!

**Comment by KC37** [comment]
> 
> 
> I'll have to test it a bit when I have a chance but if there are any changes that need to be made then don't worry about it, I'll handle them. You should focus on enjoying your graduation, and congratulations!

Thank you very much!

**Pull request closed without merging**
